### ISSUE TITLE
why isnt this on pypi?

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_Debug_I2C#15]
is there a reason for this to not be installable on linux?

@tannewt @kattni

**Comment by FoamyGuy** [comment]
It appears to be listed on pypi: https://pypi.org/project/adafruit-circuitpython-debug-i2c/

I'm able to install it successfully on Linux with `pip install adafruit-circuitpython-debug-i2c`. Have not tried to use it though.

**Comment by ladyada** [comment]
oh wierd it was totally not there i thought! could have also been a 2am thing brainsquish!
